-- Run this in your Supabase SQL Editor to set up the database.

-- 1. Server Configuration
CREATE TABLE IF NOT EXISTS server_config (
    guild_id TEXT PRIMARY KEY,
    scrim_admin_role_id TEXT,
    timezone TEXT DEFAULT 'Asia/Kolkata',
    staff_channel_id TEXT,
    results_channel_id TEXT,
    reg_channel_id TEXT,
    host_name TEXT,
    host_logo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Lobbies (Scrims)
CREATE TABLE IF NOT EXISTS lobbies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT,
    name TEXT,
    state TEXT DEFAULT 'IDLE',
    max_teams INTEGER DEFAULT 12,
    reg_start_time TEXT,
    match_start_time TEXT,
    channel_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Teams
CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id BIGINT REFERENCES lobbies(id) ON DELETE CASCADE,
    team_name TEXT,
    slot_no INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Team Players (Mapping IGNs to Teams for Deduplication)
CREATE TABLE IF NOT EXISTS team_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
    ign TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(team_id, ign)
);

-- 5. Players (Global Registry - Linking Discord to IGN)
CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT UNIQUE,
    ign TEXT,
    team_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Matches (Metadata)
CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT,
    lobby_id BIGINT REFERENCES lobbies(id) ON DELETE CASCADE,
    match_no INTEGER,
    confirmed INTEGER DEFAULT 0, -- 0 or 1
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Match Results (Stats per player per match)
CREATE TABLE IF NOT EXISTS match_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
    team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
    player_ign TEXT,
    player_discord_id TEXT,
    kills INTEGER,
    position INTEGER,
    placement_points INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Player Stats (Global Aggregation)
CREATE TABLE IF NOT EXISTS player_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT,
    guild_id TEXT,
    total_kills INTEGER DEFAULT 0,
    booyahs INTEGER DEFAULT 0,
    matches_played INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(discord_id, guild_id)
);

-- Enable Row Level Security (RLS) is recommended by Supabase, 
-- but for a bot handling everything via Service Role Key (or simple API), it's not strictly required unless you have a frontend.
-- Enabling it but allowing all access for anon/service_role for now to avoid permission issues.
ALTER TABLE server_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE lobbies ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_stats ENABLE ROW LEVEL SECURITY;

-- Policy to allow full access (Modify if you want specific rules)
CREATE POLICY "Enable all access" ON server_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON lobbies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON teams FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON team_players FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON players FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON matches FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON match_results FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON player_stats FOR ALL USING (true) WITH CHECK (true);
